# 6.1 异常的处理：抓抛的过程 尚硅谷375

## 1. 过程一：
**“抛”**，程雪在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象。并将此对象跑出。 ---这个过程理解为抛的过程。
>一旦抛出对象以后，其后的代码就不再执行。

### 关于异常对象的产生
1. 系统自动生成的异常
2. 手动的生成一个异常对象，并抛出（**throw**），（注意不是throws）

## 2. 过程二：
**"抓"**：可以理解为异常的处理方式：

1. try- catch-finally
2. throws

## 3. try - catch -finally 的使用：
```java
try{
    //可能出现异常的代码
} catch(异常类型1 变量名1){
    //处理异常的方式1
}catch(异常类型2 变量名2){
    //处理异常的方式2
}catch(异常类型3 变量名3){
    //处理异常的方式3
}
···
finally{
    //一定会执行的代码
}
```
### 1.说明：
1. finally 是可选的
2. 使用 try 将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去 catch 中进行匹配。
3. 一旦 try 中的异常对象陪陪到某一个 catch 时，就进入 catch 中进行异常的处理。 一旦处理完成，就跳出当前的 try-catch 结构，继续执行其后的代码。
>第三个是在没有 finally 的情况下

4. catch 中的异常类型如果没有字父类关系，则谁声明在上谁声明在下为所谓。
catch 中异常类型，如果满足字父类关系，则要求子类一定声明在父类的上面。否则报错

5.  在 try 结构中声明的变量，在出了 try  结构以后，就不能再被调用。 

6. try-catch-finally 结构可以嵌套

### 2. 常用异常对象处理方式：
1. 返回为String 用getMeassgae()方法
2. 直接调用 printStackTrace()

## 4. 体会
1. 使用 try-catch-finally 处理编译时异常，是得程序在编译时就不再报错，但是运行时，任然可能报错。相当于我们使用 try-catch-finally 结构，将一个编译时可能出现的异常，延迟到运行时出现。

2. 由于运行时异常比较常见，所以我们通常就不针对运行时异常编写 try-catch-finally 。针对于编译时异常，我们说一定要考虑异常的处理。

## 测试代码：
```java
package Error;

import org.junit.Test;

public class ErrorTest {

    @Test
    public void test1(){

        String str = "123";
        str = "abc";
        try {
            int num = Integer.parseInt(str); //java.lang.NumberFormatException: For input string: "abc"
            System.out.println("hello-----1");

        }catch(NumberFormatException e){
//            System.out.println("出现数值转换异常了，不要着急");

            //String getMessage();处理异常方法一：
//            System.out.println(e.getMessage());

            //printStackTrace(); 出来异常方法二：
            e.printStackTrace();

        }catch(NullPointerException e){
            System.out.println("出现空指针异常了，不要着急");
        }catch(Exception e){
            System.out.println("出现异常了，不要着急");

        }
//        System.out.println(num); //此时不能调用num，因为出了try结构
        System.out.println("hello-----2");
    }

}
```


