# 6.2 异常的处理：finally 的使用 尚硅谷376
## try-catch-finally的使用：

1. finally的使用是可选的
2. finally 中声明的是一定会被执行的代码，即使catch 中又出现异常了， try 中有 return 语句，比如： catch 中有 return 等情况。
3. 像数据库连接、输入输出流、网络编程Socket 等资源，JVM不能自动的回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在 finally 中。

## 测试代码：
```java
package Error;

import org.junit.Test;

public class FinallyTest {

    public int method(){


        try {
            int[] arr = new int[10];
            System.out.println(arr[10]);
            return 1;

        }catch(ArrayIndexOutOfBoundsException e){
            e.getStackTrace();
            return 2;

        }finally{
            System.out.println("我一定会被执行");
            return 3;
        }

    }

    @Test
    public void test1(){
        try {
            int a = 10;
            int b = 0;
            System.out.println(a / b);
        } catch(ArithmeticException e){
            e.printStackTrace();

            int[] arr = new int[10];
            System.out.println(arr[10]);

        }catch (Exception e){
            e.printStackTrace();

        }finally{
            System.out.println("我好帅啊");
        }
//        System.out.println("我好帅啊");
    }

    @Test
    public void methodTest(){
        int num = method();
        System.out.println(num);
    }

    @Test
    public void test2(){
        //尚硅谷376 14；00处
    }

}
```



